language: python
python:
- '2.7'
env:
  global:
  - secure: BxqIu8Wnq4+u8TusFUeCN5IBwrePoM+sRnnE5UGyWlpGnrCZW9xhXPeRVoPRQCZu7Ya6hj69YthW8W3arQuogukjRy9f8Rverf1IW3CTYlK2ZWpsKdPlYJMR9NWAzTE+OaC+yDuMaa+83dLF/OCiY1qWtvsBvSQEypnCdNxuPNs=
  - GIT_CONFIG_PARAMETERS="'remote.github.url=https://${TOKEN}@github.com/kontron/robotframework-snmplibrary.git'"
install: pip install -e .
script: nosetests
after_script:
- PYTHONPATH=src python -m robot.libdoc SnmpLibrary /tmp/SnmpLibrary.html
- git remote set-branches --add origin gh-pages
- git fetch origin
- git checkout gh-pages
- mv /tmp/SnmpLibrary.html .
- git add SnmpLibrary.html
- git config --global user.email "travis@travis-ci.org"
- git config --global user.name "Travis CI"
- git commit -m "autogen libdoc ($(date -R))"
- git push github gh-pages 2>&1 | grep -v http
deploy:
  provider: pypi
  user: mwalle
  password:
    secure: V/baVTBYIywdSq6USeatQQithUUeP+LgEPqMimvlS46NCyOqP63IzkfoXJmSofCRhUj4XBkauGm6xqLNho3BcsAtGxRXfx27TxEZm3IdmC4O6hHOBBC13zpqVoDy7qeonSsmXJog9f+RZcRTtmTVvQBQ6jBaZB1YR137cp+u438=
  on:
    tags: true
    distributions: "release"
